# db connection info & fileupload config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springreact
    username: ohgiraffers
    password: ohgiraffers
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

  # jpa config
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging Level
logging:
  level:
    root: info

## 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  ## WebConfig에 세팅
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**

  image-dir: src/main/resources/static/productimgs
  image-url: http://localhost:8080/productimgs/
jwt:
  key: wERjtIdxQ8lNjF0w/AAiN6HqTASaCAUzSq6nbKefMwf5CbPE8GvwLsClz94uVt9Q1esxYwwXVU+BYn7/mR01Qg==
  time: 1800000

## swagger 확인 url
## http://localhost:포트/swagger-ui/index.html
springdoc:
  packages-to-scan: com.ohgiraffers.restapi
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

